import type { Dicionario } from "./pt";

const en: Dicionario = {
  meta: {
    titulo: "T9 ADS Company | Paid traffic, structure and scale for your business",
    descricao:
      "We understand your business, map out the path and build paid traffic, CRM, funnels, automations and dashboards so your company can scale. Book a free consultation.",
    ogTitulo: "See what T9 does",
    ogDescricao:
      "Paid traffic, sales pages, CRM, funnels and automations. In 4 weeks, your business starts operating differently.",
  },
  nav: {
    principal: "Main",
    comoFunciona: "How it works",
    servicos: "Services",
    resultados: "Results",
    clientes: "Clients",
    metodo: "Method",
    agendar: "Book a consultation",
    agendarGratuita: "Book a free consultation",
    abrirMenu: "Open menu",
    fecharMenu: "Close menu",
    idioma: "Language",
  },
  hero: {
    h1: "T9 ADS Company: paid traffic, structure and scale for your business",
    alt: "T9 ADS Company logo with Instagram, WhatsApp, Meta, Google and AI icons orbiting around it",
    texto:
      "We understand your business, map out the path and build the **traffic, sales and automation** structure that takes your company to the next level.",
    cta: "Book a free consultation",
    verComo: "See how it works",
  },
  faixaRolante: [
    "Paid Traffic",
    "Meta Ads",
    "Google Ads",
    "Sales Pages",
    "CRM",
    "Sales Funnels",
    "Automations",
    "AI Agents",
    "Central Dashboard",
  ],
  entender: {
    eyebrow: "How T9 works",
    tresEtapas: "Three steps. No magic formula.",
    faixa: "Understand",
    titulo: "It all starts with alignment.",
    subtitulo: "We hold a meeting to understand your entire business, your market and your goals.",
    itens: [
      "Sales Process",
      "Marketing Investment",
      "Average Ticket",
      "Target Audience",
      "Your Numbers",
      "Market Research",
      "Bottlenecks and Opportunities",
      "Current Operation",
    ],
    rodape: "Before we advertise, we need to know **exactly** what we are building.",
  },
  estruturar: {
    faixa: "Structure",
    titulo: "We map out the path for your company to go further.",
    subtitulo:
      "We identify what is holding you back and structure everything that needs to be created, fixed and optimized.",
    pontos: ["Today", "Diagnosis", "Priorities", "Structure", "Execution", "Goal"],
    destaque: "No **magic formula**. We **build everything from scratch**, with your **business** in mind.",
  },
  construir: {
    faixa: "Build",
    titulo: "We build the structure that takes your company to the next level.",
    servicos: [
      { titulo: "Paid Traffic", texto: "Meta Ads and Google Ads campaigns focused on sales, not likes." },
      { titulo: "Sales Pages", texto: "Fast, persuasive pages built to turn clicks into contacts." },
      { titulo: "CRM", texto: "Every lead organized, from first contact to closing." },
      { titulo: "Sales Funnels", texto: "The right journey for each audience, from the ad to after-sales." },
      { titulo: "Automations", texto: "Follow-ups, messages and AI agents working for you around the clock." },
      { titulo: "Central Dashboard", texto: "All your business numbers in one place, up to date and easy to read." },
    ],
    muitoMais: "And much more! Depending on your needs.",
  },
  numeros: {
    eyebrow: "Results",
    titulo: "Our clients' trust shows in the numbers.",
    texto: "Many clients trust T9 with significant ad investments every month.",
    cta: "I want these results for my business",
    valorGasto: "Amount spent",
    painel: "Ads Manager · Campaigns",
    meses: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
  },
  clientes: {
    eyebrow: "Clients",
    titulo: "Operations that started running as a system, in four countries.",
  },
  feedbacks: {
    eyebrow: "Testimonials",
    titulo: "Feedback that drives us.",
    subtitulo: "Beyond the numbers, see the impact we make on partner businesses through stories like these:",
    nota: "Real messages from clients. Names and brands have been hidden to protect their privacy.",
    notaIdioma: "Messages shown in their original Portuguese.",
  },
  metodo: {
    faixa: "For businesses with revenue above R$ 40,000/month",
    titulo: "In 4 weeks, your company starts operating differently.",
    texto: "A straightforward method with weekly deliverables, closely managed by people who know traffic and sales.",
    cta: "Start with the free consultation",
    semana: "Week {n}",
    semanas: [
      {
        titulo: "Diagnosis and setup",
        texto: "We get to know your whole business and market, and run a survey to define goals and campaigns.",
      },
      {
        titulo: "Structure and testing",
        texto:
          "We create everything needed to reach the goal: CRM, sales page, ads, copy, AI agents and whatever else it takes.",
      },
      { titulo: "Implementation", texto: "With everything created, tested and approved, we take the whole structure live." },
      {
        titulo: "Optimization and scale",
        texto: "Daily optimizations, projections for the coming months and scaling of results.",
      },
    ],
  },
  agendamento: {
    titulo: "Let's understand your business and create",
    tituloDestaque: "an action plan to scale your revenue.",
    texto:
      "In a **free consultation** with no commitment, we analyze your current situation and define a **personalized marketing plan** for your company.",
    beneficios: ["Analysis of your current situation", "Personalized action plan", "Free and no commitment"],
    etapas: ["Your details", "Date and time", "Confirmed"],
    etapasAria: "Booking steps",
    formTitulo: "Book your free consultation",
    formSub: "It takes less than a minute. Then you pick the best time.",
    nome: "Name",
    nomeExemplo: "Your full name",
    email: "Email",
    emailExemplo: "you@company.com",
    whatsapp: "WhatsApp",
    whatsappExemplo: "+1 305 555 0123",
    whatsappDica: "Include your country code (e.g. +1 for the US, +55 for Brazil).",
    faturamento: "Monthly revenue",
    opcional: "(optional)",
    faixaExemplo: "Select a range",
    faixas: [
      "Up to R$ 40k/month",
      "R$ 40k to R$ 100k/month",
      "R$ 100k to R$ 300k/month",
      "R$ 300k to R$ 1M/month",
      "Over R$ 1M/month",
    ],
    escolherHorario: "Choose date and time",
    privacidade: "Your data stays with T9. No spam.",
    erroNome: "Please tell us your name.",
    erroEmail: "This email doesn't look valid.",
    erroWhatsapp: "Enter your WhatsApp number with the country code.",
    erroHorario: "Choose a day and a time.",
    erroCampos: "Please check the highlighted fields.",
    erroEnvio: "We couldn't save this right now. Please try again in a moment.",
    voltar: "Back",
    horarioTituloNome: "{nome}, what time works best?",
    horarioTitulo: "What time works best?",
    horarioSub: "45-minute online meeting. Times shown in Brasília time (UTC−3).",
    dia: "Day",
    horario: "Time",
    diasAria: "Available days",
    horariosAria: "Available times",
    suaReuniao: "Your meeting:",
    escolhaDiaHorario: "Choose a day and a time.",
    agendando: "Booking...",
    confirmar: "Confirm booking",
    quando: "{data} at {hora}",
    confirmadoTitulo: "Meeting booked!",
    confirmadoTextoNome:
      "{nome}, your free consultation is set for **{quando}** (Brasília time). Our team will confirm on WhatsApp and send you the meeting link.",
    confirmadoTexto:
      "Your free consultation is set for **{quando}** (Brasília time). Our team will confirm on WhatsApp and send you the meeting link.",
    confirmarWhatsapp: "Confirm on WhatsApp",
    salvarAgenda: "Add to my calendar",
    agendaTitulo: "Free consultation | T9 ADS Company",
    agendaDetalhes: "Diagnostic meeting with T9 to understand your business and build an action plan.",
    whatsappMensagem: "Hi, T9! I'm {nome} and I just booked the free consultation for {quando} (Brasília time).",
  },
  gerenciador: {
    titulo: "Ads Manager",
    criar: "+ Create",
    custoPorResultado: "Cost per result",
    valorGasto: "Amount spent",
    porContato: "Per website contact",
    porCompra: "Per purchase",
    aria: "Meta Ads Manager: {custo} per website contact and {gasto} amount spent",
  },
  rodape: {
    descricao: "Paid traffic, sales structure and automations for companies that want to scale predictably.",
    direitos: "All rights reserved.",
    aria: "Footer",
  },
};

export default en;
