import type { Dicionario } from "./pt";

const es: Dicionario = {
  meta: {
    titulo: "T9 ADS Company | Tráfico pago, estructura y escala para tu empresa",
    descricao:
      "Entendemos tu negocio, trazamos el camino y construimos tráfico pago, CRM, embudos, automatizaciones y dashboards para que tu empresa escale. Agenda una consultoría gratuita.",
    ogTitulo: "Descubre lo que hace T9",
    ogDescricao:
      "Tráfico pago, páginas de ventas, CRM, embudos y automatizaciones. En 4 semanas, tu empresa empieza a operar de otra forma.",
  },
  nav: {
    principal: "Principal",
    comoFunciona: "Cómo funciona",
    servicos: "Servicios",
    resultados: "Resultados",
    clientes: "Clientes",
    metodo: "Método",
    agendar: "Agendar consultoría",
    agendarGratuita: "Agendar consultoría gratuita",
    abrirMenu: "Abrir menú",
    fecharMenu: "Cerrar menú",
    idioma: "Idioma",
  },
  hero: {
    h1: "T9 ADS Company: tráfico pago, estructura y escala para tu empresa",
    alt: "Logo de T9 ADS Company con los íconos de Instagram, WhatsApp, Meta, Google e IA orbitando alrededor",
    texto:
      "Entendemos tu negocio, trazamos el camino y construimos la estructura de **tráfico, ventas y automatización** que lleva a tu empresa a otro nivel.",
    cta: "Agendar consultoría gratuita",
    verComo: "Ver cómo funciona",
  },
  faixaRolante: [
    "Tráfico Pago",
    "Meta Ads",
    "Google Ads",
    "Páginas de Ventas",
    "CRM",
    "Embudos de Ventas",
    "Automatizaciones",
    "Agentes de IA",
    "Dashboard Central",
  ],
  entender: {
    eyebrow: "Cómo trabaja T9",
    tresEtapas: "Tres etapas. Ninguna fórmula mágica.",
    faixa: "Entender",
    titulo: "Todo empieza con la alineación.",
    subtitulo: "Hacemos una reunión para entender todo tu negocio, tu mercado y tus objetivos.",
    itens: [
      "Proceso Comercial",
      "Inversión en Marketing",
      "Ticket Promedio",
      "Público Objetivo",
      "Tus Números",
      "Estudio de Mercado",
      "Cuellos de Botella y Oportunidades",
      "Operación Actual",
    ],
    rodape: "Antes de anunciar, necesitamos saber **exactamente** qué estamos construyendo.",
  },
  estruturar: {
    faixa: "Estructurar",
    titulo: "Trazamos el camino para que tu empresa llegue más lejos.",
    subtitulo: "Identificamos lo que te impide avanzar y estructuramos todo lo que hay que crear, corregir y optimizar.",
    pontos: ["Hoy", "Diagnóstico", "Prioridades", "Estructura", "Ejecución", "Objetivo"],
    destaque: "Sin aplicar ninguna **fórmula mágica**. **Desarrollamos todo desde cero**, pensando en tu **negocio**.",
  },
  construir: {
    faixa: "Construir",
    titulo: "Montamos la estructura que lleva a tu empresa a otro nivel.",
    servicos: [
      { titulo: "Tráfico Pago", texto: "Campañas en Meta Ads y Google Ads enfocadas en ventas, no en likes." },
      { titulo: "Páginas de Ventas", texto: "Páginas rápidas y persuasivas, hechas para convertir clics en contactos." },
      { titulo: "CRM", texto: "Todos los leads organizados, desde el primer contacto hasta el cierre." },
      { titulo: "Embudos de Ventas", texto: "El recorrido correcto para cada público, del anuncio a la posventa." },
      { titulo: "Automatizaciones", texto: "Seguimientos, mensajes y agentes de IA trabajando para ti las 24 horas." },
      { titulo: "Dashboard Central", texto: "Todos los números del negocio en un solo lugar, actualizados y fáciles de leer." },
    ],
    muitoMais: "¡Y mucho más! Según lo que necesites.",
  },
  numeros: {
    eyebrow: "Resultados",
    titulo: "La confianza de los clientes se ve en los números.",
    texto: "Muchos clientes confían a T9 altas inversiones todos los meses.",
    cta: "Quiero este resultado en mi empresa",
    valorGasto: "Importe gastado",
    painel: "Administrador de anuncios · Campañas",
    meses: ["Ene", "Feb", "Mar", "Abr", "May", "Jun"],
  },
  clientes: {
    eyebrow: "Clientes",
    titulo: "Operaciones que pasaron a funcionar como un sistema, en cuatro países.",
  },
  feedbacks: {
    eyebrow: "Testimonios",
    titulo: "Feedbacks que nos mueven.",
    subtitulo:
      "Más allá de los números, mira el impacto que generamos en las empresas aliadas a través de historias como estas:",
    nota: "Mensajes reales de clientes. Los nombres y las marcas se ocultaron para preservar su privacidad.",
    notaIdioma: "Mensajes en su idioma original (portugués).",
  },
  metodo: {
    faixa: "Para empresas que facturan más de R$ 40.000/mes",
    titulo: "En 4 semanas, tu empresa empieza a operar de otra forma.",
    texto: "Un método directo, con entregas semanales y todo acompañado de cerca por quien entiende de tráfico y ventas.",
    cta: "Empezar por la consultoría gratuita",
    semana: "Semana {n}",
    semanas: [
      {
        titulo: "Diagnóstico y configuraciones",
        texto: "Entendemos todo tu negocio y tu mercado y hacemos un relevamiento para definir objetivos y campañas.",
      },
      {
        titulo: "Estructura y pruebas",
        texto:
          "Creamos todo lo necesario para llegar al objetivo: CRM, página de ventas, anuncios, copys, agentes de IA y lo que haga falta.",
      },
      { titulo: "Implementación", texto: "Con todo creado, probado y aprobado, ponemos toda la estructura en marcha." },
      {
        titulo: "Optimización y escala",
        texto: "Optimizaciones diarias, proyecciones para los próximos meses y escala de resultados.",
      },
    ],
  },
  agendamento: {
    titulo: "Vamos a entender tu negocio y crear",
    tituloDestaque: "un plan de acción para escalar tu facturación.",
    texto:
      "En una **consultoría gratuita** y sin compromiso, analizamos tu situación actual y definimos un **plan de marketing personalizado** para tu empresa.",
    beneficios: ["Análisis de tu situación actual", "Plan de acción personalizado", "Gratis y sin compromiso"],
    etapas: ["Tus datos", "Fecha y hora", "Confirmado"],
    etapasAria: "Pasos de la reserva",
    formTitulo: "Agenda tu consultoría gratuita",
    formSub: "Toma menos de 1 minuto. Después eliges el mejor horario.",
    nome: "Nombre",
    nomeExemplo: "Tu nombre completo",
    email: "Correo electrónico",
    emailExemplo: "tu@empresa.com",
    whatsapp: "WhatsApp",
    whatsappExemplo: "+54 9 11 1234-5678",
    whatsappDica: "Incluye el código de tu país (por ejemplo, +54 para Argentina, +55 para Brasil).",
    faturamento: "Facturación mensual",
    opcional: "(opcional)",
    faixaExemplo: "Selecciona un rango",
    faixas: [
      "Hasta R$ 40 mil/mes",
      "De R$ 40 mil a R$ 100 mil/mes",
      "De R$ 100 mil a R$ 300 mil/mes",
      "De R$ 300 mil a R$ 1 millón/mes",
      "Más de R$ 1 millón/mes",
    ],
    escolherHorario: "Elegir fecha y hora",
    privacidade: "Tus datos quedan solo con T9. Nada de spam.",
    erroNome: "Cuéntanos tu nombre.",
    erroEmail: "Este correo no parece válido.",
    erroWhatsapp: "Ingresa tu WhatsApp con el código de país.",
    erroHorario: "Elige un día y un horario.",
    erroCampos: "Revisa los campos marcados.",
    erroEnvio: "No pudimos registrarlo ahora. Inténtalo de nuevo en unos instantes.",
    voltar: "Volver",
    horarioTituloNome: "{nome}, ¿cuál es el mejor horario?",
    horarioTitulo: "¿Cuál es el mejor horario?",
    horarioSub: "Reunión online de 45 minutos. Horarios de Brasilia (UTC−3).",
    dia: "Día",
    horario: "Horario",
    diasAria: "Días disponibles",
    horariosAria: "Horarios disponibles",
    suaReuniao: "Tu reunión:",
    escolhaDiaHorario: "Elige un día y un horario.",
    agendando: "Agendando...",
    confirmar: "Confirmar reserva",
    quando: "{data}, a las {hora}",
    confirmadoTitulo: "¡Reunión agendada!",
    confirmadoTextoNome:
      "{nome}, tu consultoría gratuita quedó para el **{quando}** (horario de Brasilia). Nuestro equipo la confirmará por WhatsApp y te enviará el enlace de la reunión.",
    confirmadoTexto:
      "Tu consultoría gratuita quedó para el **{quando}** (horario de Brasilia). Nuestro equipo la confirmará por WhatsApp y te enviará el enlace de la reunión.",
    confirmarWhatsapp: "Confirmar por WhatsApp",
    salvarAgenda: "Guardar en mi calendario",
    agendaTitulo: "Consultoría gratuita | T9 ADS Company",
    agendaDetalhes: "Reunión de diagnóstico con T9 para entender tu negocio y armar un plan de acción.",
    whatsappMensagem:
      "¡Hola, T9! Soy {nome} y acabo de agendar la consultoría gratuita para el {quando} (horario de Brasilia).",
  },
  gerenciador: {
    titulo: "Administrador de anuncios",
    criar: "+ Crear",
    custoPorResultado: "Costo por resultado",
    valorGasto: "Importe gastado",
    porContato: "Por contacto del sitio web",
    porCompra: "Por compra",
    aria: "Administrador de anuncios de Meta: {custo} por contacto del sitio web y {gasto} de importe gastado",
  },
  rodape: {
    descricao: "Tráfico pago, estructura comercial y automatizaciones para empresas que quieren escalar con previsibilidad.",
    direitos: "Todos los derechos reservados.",
    aria: "Pie de página",
  },
};

export default es;
