import type { Idioma } from "@/lib/i18n";

// Textos do painel do cliente. A área de gestão da T9 (/painel/admin) fica só em português.

const pt = {
  geral: {
    painel: "Painel",
    sair: "Sair",
    salvar: "Salvar",
    salvando: "Salvando...",
    salvo: "Salvo",
    voltar: "Voltar",
    conta: "Minha conta",
    gerenciar: "Gestão T9",
    trocarEmpresa: "Trocar empresa",
    semEmpresas: "Sua conta ainda não tem nenhuma empresa liberada. Fale com a equipe da T9.",
    escolherEmpresa: "Escolha a empresa",
    bancoAusente: "O banco de dados do painel ainda não está conectado.",
  },
  login: {
    titulo: "Entrar no painel",
    texto: "Digite seu e-mail. Enviamos um link de acesso, sem senha.",
    email: "E-mail",
    enviar: "Enviar link de acesso",
    enviando: "Enviando...",
    enviado: "Pronto! Se este e-mail tiver acesso ao painel, o link chega em instantes. Ele vale por 15 minutos.",
    limite: "Muitas tentativas seguidas. Aguarde alguns minutos e tente de novo.",
    emailInvalido: "Este e-mail não parece válido.",
    erro: "Não conseguimos enviar agora. Tente de novo em instantes.",
    confirmarTitulo: "Confirmar acesso",
    confirmarTexto: "Clique no botão para entrar no painel da T9.",
    confirmar: "Entrar no painel",
    linkInvalido: "Este link expirou ou já foi usado. Peça um novo.",
    pedirNovo: "Pedir novo link",
    emailAssunto: "Seu acesso ao painel da T9",
    emailTitulo: "Seu link de acesso",
    emailTexto: "Clique no botão para entrar no painel da T9 ADS Company. O link vale por {minutos} minutos e só pode ser usado uma vez.",
    emailBotao: "Entrar no painel",
    emailRodape: "Se você não pediu este acesso, é só ignorar este e-mail.",
    conviteTexto: "O painel de {empresa} na T9 ADS Company está liberado para você. Clique no botão para entrar. O link vale por 3 dias e só pode ser usado uma vez.",
  },
  menu: { visao: "Visão geral", campanhas: "Campanhas", leads: "Leads", plano: "Plano de 4 semanas" },
  periodo: {
    rotulo: "Período",
    "7": "7 dias",
    "30": "30 dias",
    "90": "90 dias",
    mes: "Este mês",
    "mes-passado": "Mês passado",
    comparacao: "vs. período anterior",
    dadosAte: "Dados até {data}",
    semDadosAinda: "Sem dados ainda",
  },
  kpi: {
    investimento: "Investimento",
    impressoes: "Impressões",
    cliques: "Cliques",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    leads: "Leads",
    cpl: "Custo por lead",
    conversoes: "Vendas",
    receita: "Receita",
    roas: "ROAS",
    ticket: "Ticket médio",
    cpa: "Custo por venda",
    taxa: "Taxa de conversão",
  },
  visao: {
    titulo: "Visão geral",
    metas: "Metas do mês",
    metaDe: "de {meta}",
    ritmo: "No ritmo atual: {valor} no mês",
    metaCpl: "Meta: até {meta}",
    semMetas: "As metas do mês ainda não foram definidas.",
    comentario: "Palavra do gestor",
    comentarioEm: "Atualizado em {data}",
    investimentoDia: "Investimento por dia",
    leadsDia: "Leads por dia",
    conversoesDia: "Vendas por dia",
    plataformas: "Por plataforma",
    semDados: "Ainda não há dados de campanhas neste período.",
    ultimosLeads: "Últimos leads",
    verTodos: "Ver todos",
  },
  campanhas: {
    titulo: "Campanhas",
    campanha: "Campanha",
    plataforma: "Plataforma",
    total: "Total",
    semDados: "Nenhuma campanha com dados neste período.",
  },
  leads: {
    titulo: "Leads",
    subtitulo: "Contatos recebidos e em que etapa do funil cada um está.",
    nome: "Nome",
    contato: "Contato",
    origem: "Origem",
    etapa: "Etapa",
    recebido: "Recebido",
    nenhum: "Nenhum lead por aqui ainda.",
    todos: "Todos",
    funil: "Funil",
    etapas: {
      novo: "Novo",
      contato: "Em contato",
      reuniao: "Reunião",
      proposta: "Proposta",
      ganho: "Fechado",
      perdido: "Perdido",
    },
    alterarEtapa: "Mudar etapa de {nome}",
  },
  plano: {
    titulo: "Plano de 4 semanas",
    subtitulo: "O que a T9 está fazendo na sua operação, semana a semana.",
    semana: "Semana {n}",
    progresso: "{feitos} de {total} concluídos",
    vazio: "O plano ainda está sendo montado pela equipe.",
    status: { pendente: "A fazer", andamento: "Em andamento", feito: "Feito" },
    semanas: ["Diagnóstico e configurações", "Estrutura e testes", "Implementação", "Otimização e escala"],
  },
  conta: {
    titulo: "Minha conta",
    idioma: "Idioma do painel",
    email: "E-mail",
    perfil: "Perfil",
    perfis: { admin: "Administrador T9", gestor: "Gestor T9", cliente: "Cliente" },
  },
  extra: {
    baixarCsv: "Baixar CSV",
    verComoCliente: "Ver como cliente",
    sairModoCliente: "Voltar à visão da equipe",
    modoClienteAviso: "Você está vendo o painel exatamente como o cliente vê.",
  },
  menu2: { criativos: "Criativos", reunioes: "Reuniões", relatorios: "Relatórios", arquivos: "Arquivos" },
  criativos: {
    titulo: "Criativos",
    subtitulo: "Os anúncios que estão no ar, os que estão em teste e os que ficaram pelo caminho.",
    grupos: { validado: "Validados", teste: "Em teste", reprovado: "Reprovados" },
    status: { validado: "Validado", teste: "Em teste", reprovado: "Reprovado" },
    descricoes: {
      validado: "Rodando com resultado comprovado",
      teste: "Rodando para validar",
      reprovado: "Pausados por não performar",
    },
    formatos: { imagem: "Imagem", video: "Vídeo", carrossel: "Carrossel" },
    vazio: "Nenhum criativo aqui ainda.",
    investido: "Investido",
    custo: "Custo por resultado",
    aprendizado: "Aprendizado",
    desde: "No ar desde {data}",
    abrir: "Ver criativo",
  },
  arquivos: {
    titulo: "Arquivos",
    subtitulo: "Envie para a equipe da T9 links do Google Drive com fotos, vídeos, logos e materiais.",
    nome: "Nome do arquivo ou pasta",
    link: "Link do Google Drive",
    nota: "Observação (opcional)",
    enviar: "Enviar link",
    enviando: "Enviando...",
    sucesso: "Link enviado para a equipe.",
    linkInvalido: "Cole um link completo, começando com https://",
    nomeObrigatorio: "Dê um nome para o arquivo.",
    dica: "No Drive, clique em Compartilhar e escolha \"Qualquer pessoa com o link\" para a equipe conseguir abrir.",
    vazio: "Nenhum arquivo enviado ainda.",
    enviadoPor: "{nome} · {data}",
    abrir: "Abrir",
    remover: "Remover",
    confirmarRemocao: "Remover este link?",
  },
  reunioes: {
    titulo: "Reuniões",
    subtitulo: "Os próximos encontros e o que foi combinado em cada um.",
    proximas: "Próximas",
    anteriores: "Anteriores",
    entrar: "Entrar na reunião",
    gravacao: "Ver gravação",
    resumo: "Resumo",
    proximosPassos: "Próximos passos",
    vazio: "Nenhuma reunião registrada ainda.",
  },
  relatorios: {
    titulo: "Relatórios mensais",
    subtitulo: "O fechamento de cada mês, com os números e a análise da equipe.",
    mes: "Mês",
    imprimir: "Salvar em PDF",
    relatorioDe: "Relatório de {mes}",
    analise: "Análise do mês",
    destaques: "Destaques",
    proximos: "Próximos passos",
    semAnalise: "A análise da equipe sobre este mês ainda não foi publicada.",
    melhores: "Campanhas do mês",
    vsAnterior: "vs. mês anterior",
    geradoEm: "Gerado em {data} · T9 ADS Company",
  },
  financeiro: {
    menu: "Financeiro",
    titulo: "Financeiro",
    subtitulo: "Seus vencimentos com a T9, o que já foi pago e como pagar.",
    proximo: "Próximo vencimento",
    emAberto: "Em aberto",
    emAtraso: "Em atraso",
    pagoAno: "Pago em {ano}",
    emDia: "Nada em aberto. Tudo em dia!",
    vencimento: "Vencimento",
    descricao: "Descrição",
    valor: "Valor",
    situacao: "Situação",
    pagar: "Pagar",
    comoPagar: "Como pagar",
    copiar: "Copiar",
    copiado: "Copiado",
    vazio: "Nenhuma cobrança registrada ainda.",
    situacoes: {
      paga: "Pago em {data}",
      hoje: "Vence hoje",
      amanha: "Vence amanhã",
      vence: "Vence em {dias} dias",
      atrasada1: "1 dia de atraso",
      atrasada: "{dias} dias de atraso",
    },
    aviso: {
      lembrete7: "Seu pagamento vence em 7 dias",
      lembrete3: "Seu pagamento vence em 3 dias",
      lembrete1: "Seu pagamento vence amanhã",
      lembrete0: "Seu pagamento vence hoje",
      lembreteTexto: "{descricao} · {valor} · vencimento em {data}.",
      atraso1: "Pagamento com 1 dia de atraso",
      atraso: "Pagamento com {dias} dias de atraso",
      atrasoTexto: "{descricao} · {valor} · venceu em {data}. Regularize para evitar a suspensão das campanhas.",
      faltam1: "Falta 1 dia para a suspensão das campanhas.",
      faltam: "Faltam {dias} dias para a suspensão das campanhas.",
      suspensao: "Pagamento com {dias} dias de atraso: as campanhas serão suspensas",
      suspensaoTexto: "{descricao} · {valor} · venceu em {data}. Como o pagamento não foi identificado, as campanhas serão suspensas até a regularização.",
      pagarAgora: "Pagar agora",
      verFinanceiro: "Ver financeiro",
      fechar: "Fechar",
      jaPaguei: "Se você já pagou, desconsidere este aviso: a confirmação pode levar até 1 dia útil.",
    },
    faixa1: "Pagamento com 1 dia de atraso.",
    faixa: "Pagamento com {dias} dias de atraso.",
    faixaSuspensao: "Pagamento com {dias} dias de atraso: as campanhas serão suspensas até a regularização.",
  },
};

export type TextosPainel = typeof pt;

const en: TextosPainel = {
  geral: {
    painel: "Dashboard",
    sair: "Sign out",
    salvar: "Save",
    salvando: "Saving...",
    salvo: "Saved",
    voltar: "Back",
    conta: "My account",
    gerenciar: "T9 management",
    trocarEmpresa: "Switch company",
    semEmpresas: "Your account doesn't have access to any company yet. Please contact the T9 team.",
    escolherEmpresa: "Choose a company",
    bancoAusente: "The dashboard database is not connected yet.",
  },
  login: {
    titulo: "Sign in to the dashboard",
    texto: "Enter your email. We'll send you a sign-in link, no password needed.",
    email: "Email",
    enviar: "Send sign-in link",
    enviando: "Sending...",
    enviado: "Done! If this email has access to the dashboard, the link will arrive shortly. It's valid for 15 minutes.",
    limite: "Too many attempts in a row. Wait a few minutes and try again.",
    emailInvalido: "This email doesn't look valid.",
    erro: "We couldn't send it right now. Please try again shortly.",
    confirmarTitulo: "Confirm sign-in",
    confirmarTexto: "Click the button to enter the T9 dashboard.",
    confirmar: "Enter the dashboard",
    linkInvalido: "This link has expired or was already used. Request a new one.",
    pedirNovo: "Request a new link",
    emailAssunto: "Your access to the T9 dashboard",
    emailTitulo: "Your sign-in link",
    emailTexto: "Click the button to enter the T9 ADS Company dashboard. The link is valid for {minutos} minutes and can only be used once.",
    emailBotao: "Enter the dashboard",
    emailRodape: "If you didn't request this, you can safely ignore this email.",
    conviteTexto: "The {empresa} dashboard at T9 ADS Company is ready for you. Click the button to enter. The link is valid for 3 days and can only be used once.",
  },
  menu: { visao: "Overview", campanhas: "Campaigns", leads: "Leads", plano: "4-week plan" },
  periodo: {
    rotulo: "Period",
    "7": "7 days",
    "30": "30 days",
    "90": "90 days",
    mes: "This month",
    "mes-passado": "Last month",
    comparacao: "vs. previous period",
    dadosAte: "Data through {data}",
    semDadosAinda: "No data yet",
  },
  kpi: {
    investimento: "Ad spend",
    impressoes: "Impressions",
    cliques: "Clicks",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    leads: "Leads",
    cpl: "Cost per lead",
    conversoes: "Sales",
    receita: "Revenue",
    roas: "ROAS",
    ticket: "Average order",
    cpa: "Cost per sale",
    taxa: "Conversion rate",
  },
  visao: {
    titulo: "Overview",
    metas: "This month's goals",
    metaDe: "of {meta}",
    ritmo: "At the current pace: {valor} this month",
    metaCpl: "Goal: up to {meta}",
    semMetas: "This month's goals haven't been set yet.",
    comentario: "From your account manager",
    comentarioEm: "Updated on {data}",
    investimentoDia: "Daily ad spend",
    leadsDia: "Daily leads",
    conversoesDia: "Daily sales",
    plataformas: "By platform",
    semDados: "There's no campaign data for this period yet.",
    ultimosLeads: "Latest leads",
    verTodos: "See all",
  },
  campanhas: {
    titulo: "Campaigns",
    campanha: "Campaign",
    plataforma: "Platform",
    total: "Total",
    semDados: "No campaigns with data in this period.",
  },
  leads: {
    titulo: "Leads",
    subtitulo: "Contacts received and where each one is in the funnel.",
    nome: "Name",
    contato: "Contact",
    origem: "Source",
    etapa: "Stage",
    recebido: "Received",
    nenhum: "No leads here yet.",
    todos: "All",
    funil: "Funnel",
    etapas: {
      novo: "New",
      contato: "Contacted",
      reuniao: "Meeting",
      proposta: "Proposal",
      ganho: "Won",
      perdido: "Lost",
    },
    alterarEtapa: "Change stage for {nome}",
  },
  plano: {
    titulo: "4-week plan",
    subtitulo: "What T9 is doing in your operation, week by week.",
    semana: "Week {n}",
    progresso: "{feitos} of {total} done",
    vazio: "The team is still putting the plan together.",
    status: { pendente: "To do", andamento: "In progress", feito: "Done" },
    semanas: ["Diagnosis and setup", "Structure and testing", "Implementation", "Optimization and scale"],
  },
  conta: {
    titulo: "My account",
    idioma: "Dashboard language",
    email: "Email",
    perfil: "Role",
    perfis: { admin: "T9 administrator", gestor: "T9 account manager", cliente: "Client" },
  },
  extra: {
    baixarCsv: "Download CSV",
    verComoCliente: "View as client",
    sairModoCliente: "Back to team view",
    modoClienteAviso: "You're seeing the dashboard exactly as the client sees it.",
  },
  menu2: { criativos: "Creatives", reunioes: "Meetings", relatorios: "Reports", arquivos: "Files" },
  criativos: {
    titulo: "Creatives",
    subtitulo: "The ads that are live, the ones being tested and the ones that didn't make it.",
    grupos: { validado: "Validated", teste: "Testing", reprovado: "Rejected" },
    status: { validado: "Validated", teste: "Testing", reprovado: "Rejected" },
    descricoes: {
      validado: "Live with proven results",
      teste: "Live and being validated",
      reprovado: "Paused for underperforming",
    },
    formatos: { imagem: "Image", video: "Video", carrossel: "Carousel" },
    vazio: "No creatives here yet.",
    investido: "Spent",
    custo: "Cost per result",
    aprendizado: "Takeaway",
    desde: "Live since {data}",
    abrir: "View creative",
  },
  arquivos: {
    titulo: "Files",
    subtitulo: "Send the T9 team Google Drive links with photos, videos, logos and materials.",
    nome: "File or folder name",
    link: "Google Drive link",
    nota: "Note (optional)",
    enviar: "Send link",
    enviando: "Sending...",
    sucesso: "Link sent to the team.",
    linkInvalido: "Paste a full link, starting with https://",
    nomeObrigatorio: "Give the file a name.",
    dica: "In Drive, click Share and choose \"Anyone with the link\" so the team can open it.",
    vazio: "No files sent yet.",
    enviadoPor: "{nome} · {data}",
    abrir: "Open",
    remover: "Remove",
    confirmarRemocao: "Remove this link?",
  },
  reunioes: {
    titulo: "Meetings",
    subtitulo: "Upcoming meetings and what was agreed in each one.",
    proximas: "Upcoming",
    anteriores: "Past",
    entrar: "Join meeting",
    gravacao: "Watch recording",
    resumo: "Summary",
    proximosPassos: "Next steps",
    vazio: "No meetings recorded yet.",
  },
  relatorios: {
    titulo: "Monthly reports",
    subtitulo: "Each month's wrap-up, with the numbers and the team's analysis.",
    mes: "Month",
    imprimir: "Save as PDF",
    relatorioDe: "{mes} report",
    analise: "Monthly analysis",
    destaques: "Highlights",
    proximos: "Next steps",
    semAnalise: "The team's analysis for this month hasn't been published yet.",
    melhores: "Campaigns this month",
    vsAnterior: "vs. previous month",
    geradoEm: "Generated on {data} · T9 ADS Company",
  },
  financeiro: {
    menu: "Billing",
    titulo: "Billing",
    subtitulo: "Your due dates with T9, what has been paid and how to pay.",
    proximo: "Next due date",
    emAberto: "Open",
    emAtraso: "Overdue",
    pagoAno: "Paid in {ano}",
    emDia: "Nothing open. You're all set!",
    vencimento: "Due date",
    descricao: "Description",
    valor: "Amount",
    situacao: "Status",
    pagar: "Pay",
    comoPagar: "How to pay",
    copiar: "Copy",
    copiado: "Copied",
    vazio: "No invoices yet.",
    situacoes: {
      paga: "Paid on {data}",
      hoje: "Due today",
      amanha: "Due tomorrow",
      vence: "Due in {dias} days",
      atrasada1: "1 day overdue",
      atrasada: "{dias} days overdue",
    },
    aviso: {
      lembrete7: "Your payment is due in 7 days",
      lembrete3: "Your payment is due in 3 days",
      lembrete1: "Your payment is due tomorrow",
      lembrete0: "Your payment is due today",
      lembreteTexto: "{descricao} · {valor} · due on {data}.",
      atraso1: "Payment 1 day overdue",
      atraso: "Payment {dias} days overdue",
      atrasoTexto: "{descricao} · {valor} · was due on {data}. Please settle it to avoid having your campaigns paused.",
      faltam1: "1 day left before campaigns are paused.",
      faltam: "{dias} days left before campaigns are paused.",
      suspensao: "Payment {dias} days overdue: campaigns will be paused",
      suspensaoTexto: "{descricao} · {valor} · was due on {data}. Since the payment hasn't been received, campaigns will be paused until it is settled.",
      pagarAgora: "Pay now",
      verFinanceiro: "View billing",
      fechar: "Close",
      jaPaguei: "If you've already paid, please disregard this notice: confirmation can take up to 1 business day.",
    },
    faixa1: "Payment 1 day overdue.",
    faixa: "Payment {dias} days overdue.",
    faixaSuspensao: "Payment {dias} days overdue: campaigns will be paused until it is settled.",
  },
};

const es: TextosPainel = {
  geral: {
    painel: "Panel",
    sair: "Salir",
    salvar: "Guardar",
    salvando: "Guardando...",
    salvo: "Guardado",
    voltar: "Volver",
    conta: "Mi cuenta",
    gerenciar: "Gestión T9",
    trocarEmpresa: "Cambiar empresa",
    semEmpresas: "Tu cuenta todavía no tiene ninguna empresa habilitada. Habla con el equipo de T9.",
    escolherEmpresa: "Elige la empresa",
    bancoAusente: "La base de datos del panel todavía no está conectada.",
  },
  login: {
    titulo: "Entrar al panel",
    texto: "Escribe tu correo. Te enviamos un enlace de acceso, sin contraseña.",
    email: "Correo electrónico",
    enviar: "Enviar enlace de acceso",
    enviando: "Enviando...",
    enviado: "¡Listo! Si este correo tiene acceso al panel, el enlace llegará en instantes. Es válido por 15 minutos.",
    limite: "Demasiados intentos seguidos. Espera unos minutos y vuelve a intentarlo.",
    emailInvalido: "Este correo no parece válido.",
    erro: "No pudimos enviarlo ahora. Inténtalo de nuevo en unos instantes.",
    confirmarTitulo: "Confirmar acceso",
    confirmarTexto: "Haz clic en el botón para entrar al panel de T9.",
    confirmar: "Entrar al panel",
    linkInvalido: "Este enlace expiró o ya se usó. Pide uno nuevo.",
    pedirNovo: "Pedir un enlace nuevo",
    emailAssunto: "Tu acceso al panel de T9",
    emailTitulo: "Tu enlace de acceso",
    emailTexto: "Haz clic en el botón para entrar al panel de T9 ADS Company. El enlace es válido por {minutos} minutos y solo se puede usar una vez.",
    emailBotao: "Entrar al panel",
    emailRodape: "Si no pediste este acceso, puedes ignorar este correo.",
    conviteTexto: "El panel de {empresa} en T9 ADS Company ya está habilitado para ti. Haz clic en el botón para entrar. El enlace es válido por 3 días y solo se puede usar una vez.",
  },
  menu: { visao: "Resumen", campanhas: "Campañas", leads: "Leads", plano: "Plan de 4 semanas" },
  periodo: {
    rotulo: "Período",
    "7": "7 días",
    "30": "30 días",
    "90": "90 días",
    mes: "Este mes",
    "mes-passado": "Mes pasado",
    comparacao: "vs. período anterior",
    dadosAte: "Datos hasta {data}",
    semDadosAinda: "Aún sin datos",
  },
  kpi: {
    investimento: "Inversión",
    impressoes: "Impresiones",
    cliques: "Clics",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    leads: "Leads",
    cpl: "Costo por lead",
    conversoes: "Ventas",
    receita: "Ingresos",
    roas: "ROAS",
    ticket: "Ticket promedio",
    cpa: "Costo por venta",
    taxa: "Tasa de conversión",
  },
  visao: {
    titulo: "Resumen",
    metas: "Metas del mes",
    metaDe: "de {meta}",
    ritmo: "Al ritmo actual: {valor} en el mes",
    metaCpl: "Meta: hasta {meta}",
    semMetas: "Las metas del mes todavía no se definieron.",
    comentario: "Palabra del gestor",
    comentarioEm: "Actualizado el {data}",
    investimentoDia: "Inversión por día",
    leadsDia: "Leads por día",
    conversoesDia: "Ventas por día",
    plataformas: "Por plataforma",
    semDados: "Todavía no hay datos de campañas en este período.",
    ultimosLeads: "Últimos leads",
    verTodos: "Ver todos",
  },
  campanhas: {
    titulo: "Campañas",
    campanha: "Campaña",
    plataforma: "Plataforma",
    total: "Total",
    semDados: "Ninguna campaña con datos en este período.",
  },
  leads: {
    titulo: "Leads",
    subtitulo: "Contactos recibidos y en qué etapa del embudo está cada uno.",
    nome: "Nombre",
    contato: "Contacto",
    origem: "Origen",
    etapa: "Etapa",
    recebido: "Recibido",
    nenhum: "Todavía no hay leads aquí.",
    todos: "Todos",
    funil: "Embudo",
    etapas: {
      novo: "Nuevo",
      contato: "En contacto",
      reuniao: "Reunión",
      proposta: "Propuesta",
      ganho: "Cerrado",
      perdido: "Perdido",
    },
    alterarEtapa: "Cambiar etapa de {nome}",
  },
  plano: {
    titulo: "Plan de 4 semanas",
    subtitulo: "Lo que T9 está haciendo en tu operación, semana a semana.",
    semana: "Semana {n}",
    progresso: "{feitos} de {total} completados",
    vazio: "El equipo todavía está armando el plan.",
    status: { pendente: "Por hacer", andamento: "En curso", feito: "Hecho" },
    semanas: ["Diagnóstico y configuraciones", "Estructura y pruebas", "Implementación", "Optimización y escala"],
  },
  conta: {
    titulo: "Mi cuenta",
    idioma: "Idioma del panel",
    email: "Correo electrónico",
    perfil: "Perfil",
    perfis: { admin: "Administrador T9", gestor: "Gestor T9", cliente: "Cliente" },
  },
  extra: {
    baixarCsv: "Descargar CSV",
    verComoCliente: "Ver como cliente",
    sairModoCliente: "Volver a la vista del equipo",
    modoClienteAviso: "Estás viendo el panel exactamente como lo ve el cliente.",
  },
  menu2: { criativos: "Creatividades", reunioes: "Reuniones", relatorios: "Informes", arquivos: "Archivos" },
  criativos: {
    titulo: "Creatividades",
    subtitulo: "Los anuncios activos, los que están en prueba y los que quedaron en el camino.",
    grupos: { validado: "Validadas", teste: "En prueba", reprovado: "Descartadas" },
    status: { validado: "Validada", teste: "En prueba", reprovado: "Descartada" },
    descricoes: {
      validado: "Activas con resultados comprobados",
      teste: "Activas para validar",
      reprovado: "Pausadas por bajo rendimiento",
    },
    formatos: { imagem: "Imagen", video: "Video", carrossel: "Carrusel" },
    vazio: "Todavía no hay creatividades aquí.",
    investido: "Invertido",
    custo: "Costo por resultado",
    aprendizado: "Aprendizaje",
    desde: "Activa desde {data}",
    abrir: "Ver creatividad",
  },
  arquivos: {
    titulo: "Archivos",
    subtitulo: "Envía al equipo de T9 enlaces de Google Drive con fotos, videos, logos y materiales.",
    nome: "Nombre del archivo o carpeta",
    link: "Enlace de Google Drive",
    nota: "Observación (opcional)",
    enviar: "Enviar enlace",
    enviando: "Enviando...",
    sucesso: "Enlace enviado al equipo.",
    linkInvalido: "Pega un enlace completo, que empiece con https://",
    nomeObrigatorio: "Ponle un nombre al archivo.",
    dica: "En Drive, haz clic en Compartir y elige \"Cualquier persona con el enlace\" para que el equipo pueda abrirlo.",
    vazio: "Todavía no se envió ningún archivo.",
    enviadoPor: "{nome} · {data}",
    abrir: "Abrir",
    remover: "Quitar",
    confirmarRemocao: "¿Quitar este enlace?",
  },
  reunioes: {
    titulo: "Reuniones",
    subtitulo: "Los próximos encuentros y lo que se acordó en cada uno.",
    proximas: "Próximas",
    anteriores: "Anteriores",
    entrar: "Entrar a la reunión",
    gravacao: "Ver grabación",
    resumo: "Resumen",
    proximosPassos: "Próximos pasos",
    vazio: "Todavía no hay reuniones registradas.",
  },
  relatorios: {
    titulo: "Informes mensuales",
    subtitulo: "El cierre de cada mes, con los números y el análisis del equipo.",
    mes: "Mes",
    imprimir: "Guardar en PDF",
    relatorioDe: "Informe de {mes}",
    analise: "Análisis del mes",
    destaques: "Destacados",
    proximos: "Próximos pasos",
    semAnalise: "El análisis del equipo sobre este mes todavía no se publicó.",
    melhores: "Campañas del mes",
    vsAnterior: "vs. mes anterior",
    geradoEm: "Generado el {data} · T9 ADS Company",
  },
  financeiro: {
    menu: "Finanzas",
    titulo: "Finanzas",
    subtitulo: "Tus vencimientos con T9, lo que ya se pagó y cómo pagar.",
    proximo: "Próximo vencimiento",
    emAberto: "Pendiente",
    emAtraso: "Vencido",
    pagoAno: "Pagado en {ano}",
    emDia: "Nada pendiente. ¡Todo al día!",
    vencimento: "Vencimiento",
    descricao: "Descripción",
    valor: "Monto",
    situacao: "Estado",
    pagar: "Pagar",
    comoPagar: "Cómo pagar",
    copiar: "Copiar",
    copiado: "Copiado",
    vazio: "Todavía no hay cobros registrados.",
    situacoes: {
      paga: "Pagado el {data}",
      hoje: "Vence hoy",
      amanha: "Vence mañana",
      vence: "Vence en {dias} días",
      atrasada1: "1 día de atraso",
      atrasada: "{dias} días de atraso",
    },
    aviso: {
      lembrete7: "Tu pago vence en 7 días",
      lembrete3: "Tu pago vence en 3 días",
      lembrete1: "Tu pago vence mañana",
      lembrete0: "Tu pago vence hoy",
      lembreteTexto: "{descricao} · {valor} · vence el {data}.",
      atraso1: "Pago con 1 día de atraso",
      atraso: "Pago con {dias} días de atraso",
      atrasoTexto: "{descricao} · {valor} · venció el {data}. Regulariza el pago para evitar la suspensión de las campañas.",
      faltam1: "Falta 1 día para la suspensión de las campañas.",
      faltam: "Faltan {dias} días para la suspensión de las campañas.",
      suspensao: "Pago con {dias} días de atraso: las campañas serán suspendidas",
      suspensaoTexto: "{descricao} · {valor} · venció el {data}. Como no se identificó el pago, las campañas serán suspendidas hasta la regularización.",
      pagarAgora: "Pagar ahora",
      verFinanceiro: "Ver finanzas",
      fechar: "Cerrar",
      jaPaguei: "Si ya pagaste, ignora este aviso: la confirmación puede tardar hasta 1 día hábil.",
    },
    faixa1: "Pago con 1 día de atraso.",
    faixa: "Pago con {dias} días de atraso.",
    faixaSuspensao: "Pago con {dias} días de atraso: las campañas serán suspendidas hasta la regularización.",
  },
};

export const TEXTOS_PAINEL: Record<Idioma, TextosPainel> = { pt, en, es };

export const ETAPAS_LEAD = ["novo", "contato", "reuniao", "proposta", "ganho", "perdido"] as const;
export type EtapaLead = (typeof ETAPAS_LEAD)[number];

export const STATUS_PLANO = ["pendente", "andamento", "feito"] as const;
export type StatusPlano = (typeof STATUS_PLANO)[number];

export const STATUS_CRIATIVO = ["validado", "teste", "reprovado"] as const;
export type StatusCriativo = (typeof STATUS_CRIATIVO)[number];

export const FORMATOS_CRIATIVO = ["imagem", "video", "carrossel"] as const;
export type FormatoCriativo = (typeof FORMATOS_CRIATIVO)[number];

/** Itens iniciais do plano, seguindo o método das 4 semanas do site. */
export const PLANO_PADRAO: Record<Idioma, string[][]> = {
  pt: [
    ["Reunião de diagnóstico", "Acesso às contas de anúncio, site e redes", "Pixel, API de conversões e eventos configurados", "Objetivos e campanhas definidos"],
    ["CRM configurado", "Página de vendas", "Criativos e copys", "Automações e agentes de IA"],
    ["Campanhas no ar", "Integrações conferidas de ponta a ponta", "Testes de público e criativo"],
    ["Otimizações diárias", "Projeção para os próximos meses", "Plano de escala"],
  ],
  en: [
    ["Diagnosis meeting", "Access to ad accounts, website and social media", "Pixel, Conversions API and events set up", "Goals and campaigns defined"],
    ["CRM set up", "Sales page", "Creatives and copy", "Automations and AI agents"],
    ["Campaigns live", "Integrations checked end to end", "Audience and creative tests"],
    ["Daily optimizations", "Projection for the coming months", "Scaling plan"],
  ],
  es: [
    ["Reunión de diagnóstico", "Acceso a las cuentas publicitarias, sitio y redes", "Píxel, API de conversiones y eventos configurados", "Objetivos y campañas definidos"],
    ["CRM configurado", "Página de ventas", "Creatividades y copys", "Automatizaciones y agentes de IA"],
    ["Campañas activas", "Integraciones revisadas de punta a punta", "Pruebas de público y creatividades"],
    ["Optimizaciones diarias", "Proyección para los próximos meses", "Plan de escala"],
  ],
};
