import type { Idioma } from "@/lib/i18n";

// Textos do painel do cliente. A área de gestão da T9 (/painel/admin) fica só em português.

const pt = {
  geral: {
    painel: "Painel",
    sair: "Sair",
    salvar: "Salvar",
    salvando: "Salvando...",
    salvo: "Salvo",
    voltar: "Voltar",
    conta: "Minha conta",
    gerenciar: "Gestão T9",
    trocarEmpresa: "Trocar empresa",
    semEmpresas: "Sua conta ainda não tem nenhuma empresa liberada. Fale com a equipe da T9.",
    escolherEmpresa: "Escolha a empresa",
    bancoAusente: "O banco de dados do painel ainda não está conectado.",
  },
  login: {
    titulo: "Entrar no painel",
    texto: "Digite seu e-mail. Enviamos um link de acesso, sem senha.",
    email: "E-mail",
    enviar: "Enviar link de acesso",
    enviando: "Enviando...",
    enviado: "Pronto! Se este e-mail tiver acesso ao painel, o link chega em instantes. Ele vale por 15 minutos.",
    limite: "Muitas tentativas seguidas. Aguarde alguns minutos e tente de novo.",
    emailInvalido: "Este e-mail não parece válido.",
    erro: "Não conseguimos enviar agora. Tente de novo em instantes.",
    confirmarTitulo: "Confirmar acesso",
    confirmarTexto: "Clique no botão para entrar no painel da T9.",
    confirmar: "Entrar no painel",
    linkInvalido: "Este link expirou ou já foi usado. Peça um novo.",
    pedirNovo: "Pedir novo link",
    emailAssunto: "Seu acesso ao painel da T9",
    emailTitulo: "Seu link de acesso",
    emailTexto: "Clique no botão para entrar no painel da T9 ADS Company. O link vale por {minutos} minutos e só pode ser usado uma vez.",
    emailBotao: "Entrar no painel",
    emailRodape: "Se você não pediu este acesso, é só ignorar este e-mail.",
    conviteTexto: "O painel de {empresa} na T9 ADS Company está liberado para você. Clique no botão para entrar. O link vale por 3 dias e só pode ser usado uma vez.",
  },
  menu: { visao: "Visão geral", campanhas: "Campanhas", leads: "Leads", plano: "Plano de 4 semanas" },
  periodo: {
    rotulo: "Período",
    "7": "7 dias",
    "30": "30 dias",
    "90": "90 dias",
    mes: "Este mês",
    "mes-passado": "Mês passado",
    comparacao: "vs. período anterior",
    dadosAte: "Dados até {data}",
    semDadosAinda: "Sem dados ainda",
  },
  kpi: {
    investimento: "Investimento",
    impressoes: "Impressões",
    cliques: "Cliques",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    leads: "Leads",
    cpl: "Custo por lead",
    conversoes: "Vendas",
    receita: "Receita",
    roas: "ROAS",
    ticket: "Ticket médio",
    cpa: "Custo por venda",
    taxa: "Taxa de conversão",
  },
  visao: {
    titulo: "Visão geral",
    metas: "Metas do mês",
    metaDe: "de {meta}",
    ritmo: "No ritmo atual: {valor} no mês",
    metaCpl: "Meta: até {meta}",
    semMetas: "As metas do mês ainda não foram definidas.",
    comentario: "Palavra do gestor",
    comentarioEm: "Atualizado em {data}",
    investimentoDia: "Investimento por dia",
    leadsDia: "Leads por dia",
    conversoesDia: "Vendas por dia",
    plataformas: "Por plataforma",
    semDados: "Ainda não há dados de campanhas neste período.",
    ultimosLeads: "Últimos leads",
    verTodos: "Ver todos",
  },
  campanhas: {
    titulo: "Campanhas",
    campanha: "Campanha",
    plataforma: "Plataforma",
    total: "Total",
    semDados: "Nenhuma campanha com dados neste período.",
  },
  leads: {
    titulo: "Leads",
    subtitulo: "Contatos recebidos e em que etapa do funil cada um está.",
    nome: "Nome",
    contato: "Contato",
    origem: "Origem",
    etapa: "Etapa",
    recebido: "Recebido",
    nenhum: "Nenhum lead por aqui ainda.",
    todos: "Todos",
    funil: "Funil",
    etapas: {
      novo: "Novo",
      contato: "Em contato",
      reuniao: "Reunião",
      proposta: "Proposta",
      ganho: "Fechado",
      perdido: "Perdido",
    },
    alterarEtapa: "Mudar etapa de {nome}",
  },
  plano: {
    titulo: "Plano de 4 semanas",
    subtitulo: "O que a T9 está fazendo na sua operação, semana a semana.",
    semana: "Semana {n}",
    progresso: "{feitos} de {total} concluídos",
    vazio: "O plano ainda está sendo montado pela equipe.",
    status: { pendente: "A fazer", andamento: "Em andamento", feito: "Feito" },
    semanas: ["Diagnóstico e configurações", "Estrutura e testes", "Implementação", "Otimização e escala"],
  },
  conta: {
    titulo: "Minha conta",
    idioma: "Idioma do painel",
    email: "E-mail",
    perfil: "Perfil",
    perfis: { admin: "Administrador T9", gestor: "Gestor T9", cliente: "Cliente" },
  },
};

export type TextosPainel = typeof pt;

const en: TextosPainel = {
  geral: {
    painel: "Dashboard",
    sair: "Sign out",
    salvar: "Save",
    salvando: "Saving...",
    salvo: "Saved",
    voltar: "Back",
    conta: "My account",
    gerenciar: "T9 management",
    trocarEmpresa: "Switch company",
    semEmpresas: "Your account doesn't have access to any company yet. Please contact the T9 team.",
    escolherEmpresa: "Choose a company",
    bancoAusente: "The dashboard database is not connected yet.",
  },
  login: {
    titulo: "Sign in to the dashboard",
    texto: "Enter your email. We'll send you a sign-in link, no password needed.",
    email: "Email",
    enviar: "Send sign-in link",
    enviando: "Sending...",
    enviado: "Done! If this email has access to the dashboard, the link will arrive shortly. It's valid for 15 minutes.",
    limite: "Too many attempts in a row. Wait a few minutes and try again.",
    emailInvalido: "This email doesn't look valid.",
    erro: "We couldn't send it right now. Please try again shortly.",
    confirmarTitulo: "Confirm sign-in",
    confirmarTexto: "Click the button to enter the T9 dashboard.",
    confirmar: "Enter the dashboard",
    linkInvalido: "This link has expired or was already used. Request a new one.",
    pedirNovo: "Request a new link",
    emailAssunto: "Your access to the T9 dashboard",
    emailTitulo: "Your sign-in link",
    emailTexto: "Click the button to enter the T9 ADS Company dashboard. The link is valid for {minutos} minutes and can only be used once.",
    emailBotao: "Enter the dashboard",
    emailRodape: "If you didn't request this, you can safely ignore this email.",
    conviteTexto: "The {empresa} dashboard at T9 ADS Company is ready for you. Click the button to enter. The link is valid for 3 days and can only be used once.",
  },
  menu: { visao: "Overview", campanhas: "Campaigns", leads: "Leads", plano: "4-week plan" },
  periodo: {
    rotulo: "Period",
    "7": "7 days",
    "30": "30 days",
    "90": "90 days",
    mes: "This month",
    "mes-passado": "Last month",
    comparacao: "vs. previous period",
    dadosAte: "Data through {data}",
    semDadosAinda: "No data yet",
  },
  kpi: {
    investimento: "Ad spend",
    impressoes: "Impressions",
    cliques: "Clicks",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    leads: "Leads",
    cpl: "Cost per lead",
    conversoes: "Sales",
    receita: "Revenue",
    roas: "ROAS",
    ticket: "Average order",
    cpa: "Cost per sale",
    taxa: "Conversion rate",
  },
  visao: {
    titulo: "Overview",
    metas: "This month's goals",
    metaDe: "of {meta}",
    ritmo: "At the current pace: {valor} this month",
    metaCpl: "Goal: up to {meta}",
    semMetas: "This month's goals haven't been set yet.",
    comentario: "From your account manager",
    comentarioEm: "Updated on {data}",
    investimentoDia: "Daily ad spend",
    leadsDia: "Daily leads",
    conversoesDia: "Daily sales",
    plataformas: "By platform",
    semDados: "There's no campaign data for this period yet.",
    ultimosLeads: "Latest leads",
    verTodos: "See all",
  },
  campanhas: {
    titulo: "Campaigns",
    campanha: "Campaign",
    plataforma: "Platform",
    total: "Total",
    semDados: "No campaigns with data in this period.",
  },
  leads: {
    titulo: "Leads",
    subtitulo: "Contacts received and where each one is in the funnel.",
    nome: "Name",
    contato: "Contact",
    origem: "Source",
    etapa: "Stage",
    recebido: "Received",
    nenhum: "No leads here yet.",
    todos: "All",
    funil: "Funnel",
    etapas: {
      novo: "New",
      contato: "Contacted",
      reuniao: "Meeting",
      proposta: "Proposal",
      ganho: "Won",
      perdido: "Lost",
    },
    alterarEtapa: "Change stage for {nome}",
  },
  plano: {
    titulo: "4-week plan",
    subtitulo: "What T9 is doing in your operation, week by week.",
    semana: "Week {n}",
    progresso: "{feitos} of {total} done",
    vazio: "The team is still putting the plan together.",
    status: { pendente: "To do", andamento: "In progress", feito: "Done" },
    semanas: ["Diagnosis and setup", "Structure and testing", "Implementation", "Optimization and scale"],
  },
  conta: {
    titulo: "My account",
    idioma: "Dashboard language",
    email: "Email",
    perfil: "Role",
    perfis: { admin: "T9 administrator", gestor: "T9 account manager", cliente: "Client" },
  },
};

const es: TextosPainel = {
  geral: {
    painel: "Panel",
    sair: "Salir",
    salvar: "Guardar",
    salvando: "Guardando...",
    salvo: "Guardado",
    voltar: "Volver",
    conta: "Mi cuenta",
    gerenciar: "Gestión T9",
    trocarEmpresa: "Cambiar empresa",
    semEmpresas: "Tu cuenta todavía no tiene ninguna empresa habilitada. Habla con el equipo de T9.",
    escolherEmpresa: "Elige la empresa",
    bancoAusente: "La base de datos del panel todavía no está conectada.",
  },
  login: {
    titulo: "Entrar al panel",
    texto: "Escribe tu correo. Te enviamos un enlace de acceso, sin contraseña.",
    email: "Correo electrónico",
    enviar: "Enviar enlace de acceso",
    enviando: "Enviando...",
    enviado: "¡Listo! Si este correo tiene acceso al panel, el enlace llegará en instantes. Es válido por 15 minutos.",
    limite: "Demasiados intentos seguidos. Espera unos minutos y vuelve a intentarlo.",
    emailInvalido: "Este correo no parece válido.",
    erro: "No pudimos enviarlo ahora. Inténtalo de nuevo en unos instantes.",
    confirmarTitulo: "Confirmar acceso",
    confirmarTexto: "Haz clic en el botón para entrar al panel de T9.",
    confirmar: "Entrar al panel",
    linkInvalido: "Este enlace expiró o ya se usó. Pide uno nuevo.",
    pedirNovo: "Pedir un enlace nuevo",
    emailAssunto: "Tu acceso al panel de T9",
    emailTitulo: "Tu enlace de acceso",
    emailTexto: "Haz clic en el botón para entrar al panel de T9 ADS Company. El enlace es válido por {minutos} minutos y solo se puede usar una vez.",
    emailBotao: "Entrar al panel",
    emailRodape: "Si no pediste este acceso, puedes ignorar este correo.",
    conviteTexto: "El panel de {empresa} en T9 ADS Company ya está habilitado para ti. Haz clic en el botón para entrar. El enlace es válido por 3 días y solo se puede usar una vez.",
  },
  menu: { visao: "Resumen", campanhas: "Campañas", leads: "Leads", plano: "Plan de 4 semanas" },
  periodo: {
    rotulo: "Período",
    "7": "7 días",
    "30": "30 días",
    "90": "90 días",
    mes: "Este mes",
    "mes-passado": "Mes pasado",
    comparacao: "vs. período anterior",
    dadosAte: "Datos hasta {data}",
    semDadosAinda: "Aún sin datos",
  },
  kpi: {
    investimento: "Inversión",
    impressoes: "Impresiones",
    cliques: "Clics",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    leads: "Leads",
    cpl: "Costo por lead",
    conversoes: "Ventas",
    receita: "Ingresos",
    roas: "ROAS",
    ticket: "Ticket promedio",
    cpa: "Costo por venta",
    taxa: "Tasa de conversión",
  },
  visao: {
    titulo: "Resumen",
    metas: "Metas del mes",
    metaDe: "de {meta}",
    ritmo: "Al ritmo actual: {valor} en el mes",
    metaCpl: "Meta: hasta {meta}",
    semMetas: "Las metas del mes todavía no se definieron.",
    comentario: "Palabra del gestor",
    comentarioEm: "Actualizado el {data}",
    investimentoDia: "Inversión por día",
    leadsDia: "Leads por día",
    conversoesDia: "Ventas por día",
    plataformas: "Por plataforma",
    semDados: "Todavía no hay datos de campañas en este período.",
    ultimosLeads: "Últimos leads",
    verTodos: "Ver todos",
  },
  campanhas: {
    titulo: "Campañas",
    campanha: "Campaña",
    plataforma: "Plataforma",
    total: "Total",
    semDados: "Ninguna campaña con datos en este período.",
  },
  leads: {
    titulo: "Leads",
    subtitulo: "Contactos recibidos y en qué etapa del embudo está cada uno.",
    nome: "Nombre",
    contato: "Contacto",
    origem: "Origen",
    etapa: "Etapa",
    recebido: "Recibido",
    nenhum: "Todavía no hay leads aquí.",
    todos: "Todos",
    funil: "Embudo",
    etapas: {
      novo: "Nuevo",
      contato: "En contacto",
      reuniao: "Reunión",
      proposta: "Propuesta",
      ganho: "Cerrado",
      perdido: "Perdido",
    },
    alterarEtapa: "Cambiar etapa de {nome}",
  },
  plano: {
    titulo: "Plan de 4 semanas",
    subtitulo: "Lo que T9 está haciendo en tu operación, semana a semana.",
    semana: "Semana {n}",
    progresso: "{feitos} de {total} completados",
    vazio: "El equipo todavía está armando el plan.",
    status: { pendente: "Por hacer", andamento: "En curso", feito: "Hecho" },
    semanas: ["Diagnóstico y configuraciones", "Estructura y pruebas", "Implementación", "Optimización y escala"],
  },
  conta: {
    titulo: "Mi cuenta",
    idioma: "Idioma del panel",
    email: "Correo electrónico",
    perfil: "Perfil",
    perfis: { admin: "Administrador T9", gestor: "Gestor T9", cliente: "Cliente" },
  },
};

export const TEXTOS_PAINEL: Record<Idioma, TextosPainel> = { pt, en, es };

export const ETAPAS_LEAD = ["novo", "contato", "reuniao", "proposta", "ganho", "perdido"] as const;
export type EtapaLead = (typeof ETAPAS_LEAD)[number];

export const STATUS_PLANO = ["pendente", "andamento", "feito"] as const;
export type StatusPlano = (typeof STATUS_PLANO)[number];

/** Itens iniciais do plano, seguindo o método das 4 semanas do site. */
export const PLANO_PADRAO: Record<Idioma, string[][]> = {
  pt: [
    ["Reunião de diagnóstico", "Acesso às contas de anúncio, site e redes", "Pixel, API de conversões e eventos configurados", "Objetivos e campanhas definidos"],
    ["CRM configurado", "Página de vendas", "Criativos e copys", "Automações e agentes de IA"],
    ["Campanhas no ar", "Integrações conferidas de ponta a ponta", "Testes de público e criativo"],
    ["Otimizações diárias", "Projeção para os próximos meses", "Plano de escala"],
  ],
  en: [
    ["Diagnosis meeting", "Access to ad accounts, website and social media", "Pixel, Conversions API and events set up", "Goals and campaigns defined"],
    ["CRM set up", "Sales page", "Creatives and copy", "Automations and AI agents"],
    ["Campaigns live", "Integrations checked end to end", "Audience and creative tests"],
    ["Daily optimizations", "Projection for the coming months", "Scaling plan"],
  ],
  es: [
    ["Reunión de diagnóstico", "Acceso a las cuentas publicitarias, sitio y redes", "Píxel, API de conversiones y eventos configurados", "Objetivos y campañas definidos"],
    ["CRM configurado", "Página de ventas", "Creatividades y copys", "Automatizaciones y agentes de IA"],
    ["Campañas activas", "Integraciones revisadas de punta a punta", "Pruebas de público y creatividades"],
    ["Optimizaciones diarias", "Proyección para los próximos meses", "Plan de escala"],
  ],
};
